-- Align media asset embeddings with voyage-4-lite 1024-dimensional output.
-- Any vectors generated by earlier model experiments are cleared so the
-- reconciliation job can regenerate them with the current model.
DROP INDEX IF EXISTS idx_media_assets_embedding;

ALTER TABLE media_assets
    ALTER COLUMN embedding TYPE VECTOR(1024)
    USING NULL::VECTOR(1024);

CREATE INDEX IF NOT EXISTS idx_media_assets_embedding
    ON media_assets USING ivfflat (embedding vector_cosine_ops)
    WITH (lists = 100)
    WHERE embedding IS NOT NULL;
